[connections.postgresql]
dialect = "postgresql"
host = "dpg-crjmj7u8ii6s73fhr7r0-a.ohio-postgres.render.com"
port = "5432"
database = "scorecard_software"
username = "ricardo_sojo"
password = "FF73FVSlXZbzP2WAL2IG6rE7xN7zbYt0"
